### ISSUE TITLE
export 'defineInjectable' was not found in '@angular/core'

### ISSUE THREAD

**Issue by amitthk** [valor-software/ng2-charts#1261]
**export 'defineInjectable' was not found in '@angular/core'**

I am getting this error when I'm trying to run  ng2-charts.

```
WARNING in ./node_modules/ng2-charts/fesm5/ng2-charts.js
230:54-70 "export 'defineInjectable' was not found in '@angular/core'
    at HarmonyImportSpecifierDependency._getErrors (C:\Users\amitthk\Documents\projects\google_bitbucket\amitthk\coredashb-ansible\coredashb-ui-onb\node_modules\@angular\cli\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:65:15)
    at HarmonyImportSpecifierDependency.getWarnings (C:\Users\amitthk\Documents\projects\google_bitbucket\amitthk\coredashb-ansible\coredashb-ui-onb\node_modules\@angular\cli\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:39:15)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\amitthk\Documents\projects\google_bitbucket\amitthk\coredashb-ansible\coredashb-ui-onb\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Users\amitthk\Documents\projects\google_bitbucket\amitthk\coredashb-ansible\coredashb-ui-onb\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:561:9)
    at C:\Users\amitthk\Documents\projects\google_bitbucket\amitthk\coredashb-ansible\coredashb-ui-onb\node_modules\@angular\cli\node_modules\webpack\lib\Compiler.js:502:17
    at C:\Users\amitthk\Documents\projects\google_bitbucket\amitthk\coredashb-ansible\coredashb-ui-onb\node_modules\tapable\lib\Tapable.js:289:11
    at C:\Users\amitthk\Documents\projects\google_bitbucket\amitthk\coredashb-ansible\coredashb-ui-onb\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:507:11
    at C:\Users\amitthk\Documents\projects\google_bitbucket\amitthk\coredashb-ansible\coredashb-ui-onb\node_modules\@angular\cli\node_modules\webpack\lib\Compilation.js:477:14
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
 @ ./node_modules/ng2-charts/fesm5/ng2-charts.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

My project.js has following :
```
"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.0.1",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.0.1",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angular2-notifications": "^2.0.0",
    "chart.js": "^2.9.3",
    "core-js": "^2.4.1",
    "ng2-charts": "^2.2.3",
    "rxjs": "^5.5.6",
    "underscore": "^1.8.0",
    "webpack": "^3.11.0",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "1.6.8",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "2.8.9",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
```

Please help!

**Comment by amitthk** [comment]
I figured it out.  I realized I am on @angular/5.2.0  so downgraded to a compatible ng2-charts

```
npm install ng2-charts@1.6.0 --save
npm install chart.js --save
```
