### ISSUE TITLE
Jest error with Angular 11

### ISSUE THREAD

**Issue by ThomasDevens** [valor-software/ng2-charts#1291]
Having an issue with Jest testing after upgrading to Angular 11 and ng2-charts v2.4+

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    {path_to_project}\node_modules\lodash-es\lodash.js:10
    export { default as add } from './add.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at node_modules/ng2-charts/bundles/ng2-charts.umd.js:2:153
      at Object.<anonymous> (node_modules/ng2-charts/bundles/ng2-charts.umd.js:5:2)
```

Some have suggested clearing the jest cache as a simple solution, but I haven't had any luck with that. I'm not sure if this is an issue in ng2-charts (and if it's fixed in an upcoming release?) or if there is some Jest config I need to update for this.

**Comment by krishna-andola** [comment]
I am also facing the same issue with Angular 11, Jest v.26.6.2, and ng2-charts v2.4.2. Do you have any luck?

**Comment by cvocvo** [comment]
Also running into this issue; does anyone know how to fix?

**Comment by jpike88** [comment]
ditching lodash sounds like a better idea.

**Comment by cerireyhan** [comment]
Is there any update on this?

**Comment by ThomasDevens** [comment]
#1303 - Can we get this patched into the v2 version? Might fix this issue

**Comment by santam85** [comment]
Could any of you share a repo with a minimal reproduction example? Not convinced lodash-es is the issue here...

**Comment by ThomasDevens** [comment]
Finally got around to looking into this again - as I kind of figured, there is a jest config fix that seems to have solved this for me: https://stackoverflow.com/questions/42260218/jest-setup-syntaxerror-unexpected-token-export
