### ISSUE TITLE
Upgrading from 2.3.3 to 2.4.2: Error: getInternalNameOfClass() called on a non-ES5 class: expected ThemeService to have an inner class declaration

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [valor-software/ng2-charts#1306]
When upgrading from 2.3.3 to 2.4.2 I'm getting:

```
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected ThemeService to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/ngcc/src/host/esm5_host.js:88:23)
    at DelegatingReflectionHost.getInternalNameOfClass (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/ngcc/src/host/delegating_host.js:89:34)
    at extractInjectableMetadata (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:125:69)
    at InjectableDecoratorHandler.analyze (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/injectable.js:66:24)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:345:40)
    at analyze (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:297:58)
    at _loop_1 (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:319:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:325:35)
    at NgccTraitCompiler.analyzeFile (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/ngcc/src/analysis/ngcc_trait_compiler.js:47:26)
    at DecorationAnalyzer.analyzeProgram (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/ngcc/src/analysis/decoration_analyzer.js:134:39)
    at ClusterMaster.onWorkerMessage (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:194:27)
    at /home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:54:95
    at ClusterMaster.<anonymous> (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:292:57)
    at step (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/tslib/tslib.js:141:27)
    at Object.next (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/tslib/tslib.js:122:57)
    at /home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/tslib/tslib.js:111:16)
    at EventEmitter.<anonymous> (/home/jbodnar/git/donation-forms/skyux-spa-donation-forms/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:286:32)
    at EventEmitter.emit (events.js:189:13)

```

There were two other issues with similar errors that have been closed. I've followed the instructions from them and added `ThemeService` as a provider in `app-extras.modules.ts`:

```
@NgModule({
  providers: [
    ThemeService,
    ...
```

as well as the component that is using the charts:

```
@Component({
  selector: 'performance-graph',
  templateUrl: './performance-graph.component.html',
  styleUrls: ['./performance-graph.component.scss'],
  providers: [ThemeService]
})
```

Neither has fixed the issue.

**Comment by dostarora97** [comment]
try running `ngcc` command in terminal after installing.
