### ISSUE TITLE
Jest test end with "ReferenceError: Cannot access 'NgChartsConfiguration' before initialization" error

### ISSUE THREAD

**Issue by miwaniak** [valor-software/ng2-charts#1354]
For ng2-charts 3.0.1 when run jest test i'v got error: 

`

    ReferenceError: Cannot access 'NgChartsConfiguration' before initialization

      1 | import { ComponentFixture, TestBed } from '@angular/core/testing';
      2 | import { MockModule } from 'ng-mocks';
    > 3 | import { NgChartsModule } from 'ng2-charts';
        | ^
      4 |
      5 | import { GradeDistriburionChartComponent } from './grade-distriburion-chart.component';
      6 |

      at Object.<anonymous> (../../../../node_modules/ng2-charts/fesm2015/ng2-charts.mjs:256:140)
      at Object.<anonymous> (src/lib/grade-distriburion-chart/grade-distriburion-chart.component.spec.ts:3:1)
      at TestScheduler.scheduleTests (../../../../node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (../../../../node_modules/@jest/core/build/runJest.js:404:19)
`

**Comment by TediousMatt** [comment]
I have the same issue. The problem seems to be: https://github.com/valor-software/ng2-charts/blob/master/projects/ng2-charts/src/lib/ng-charts.module.ts

The "NgChartsConfiguration" is declared after "NgChartsModule" uses it. Locally switching these classes in the node_modules fixes the issue.
