### ISSUE TITLE
Generate new chart: An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by hill636** [valor-software/ng2-charts#1443]
My project is built with Angular v14.0.x, ng2-charts v3.1.2, chart.js v3.8.0, ng2charts-schematics v0.1.7.  
This appears to be a reoccurrence of issue #1368.

Generate new chart with command:
**$ ng generate ng2-charts-schematics:pie charts/sales-traffic-chart**

Result:
**An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID      
See "C:\Users\d4clerd\AppData\Local\Temp\ng-QOdc25\angular-errors.log" for further details.**

From angular-errors.log:
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ajv\dist\compile\codegen\index.js:568:18)

**Dropping "-schematics" from the above command produces the following error:**
An unhandled exception occurred: Cannot find module 'C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\ng2-charts\schematics\ng-generate\pie\index'
Require stack:
- C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\@angular\cli\src\command-builder\utilities\schematic-engine-host.js
- C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\@angular\cli\src\command-builder\schematics-command-module.js
- C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\@angular\cli\src\commands\add\cli.js     
- C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\@angular\cli\src\command-builder\command-runner.js
- C:\Users\d4clerd\Documents\DevPTS\Prototyping\AngularDashboard\store-admin-panel\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\d4clerd\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
See "C:\Users\d4clerd\AppData\Local\Temp\ng-vWLVzx\angular-errors.log" for further details.

**Comment by santam85** [comment]
ng2-charts-schematics is not maintained anymore, the schematics are included in the ng2-charts package, your command should rather be:

`ng generate ng2-charts:pie charts/sales-traffic-chart`

as you've already tried. You are now running into #1412 , working on fixing that
