### ISSUE TITLE
can't import the named export 'ɵɵngdeclarefactory' from non ecmascript module

### ISSUE THREAD

**Issue by visheshmohan** [valor-software/ng2-charts#1457]
package.json

> ...
> ...
> "dependencies": {
>     "@angular/animations": "11.2.2",
>     "@angular/cdk": "^11.2.13",
>     "@angular/common": "11.2.2",
>     "@angular/compiler": "11.2.2",
>     "@angular/core": "11.2.2",
>     "@angular/forms": "11.2.2",
>     "@angular/localize": "^11.2.2",
>     "@angular/material": "^11.2.13",
>     "@angular/platform-browser": "11.2.2",
>     "@angular/platform-browser-dynamic": "11.2.2",
>     "@angular/router": "11.2.2",
>     "@azure/msal-angular": "^2.0.0-alpha.6",
>     "@azure/msal-browser": "^2.11.2",
>     "@ng-bootstrap/ng-bootstrap": "6.0.0",
>     "bootstrap": "^5.2.0",
>     "chart.js": "^2.9.4",
>     "file-saver": "^2.0.5",
>     "ng-multiselect-dropdown": "^0.2.10",
>     "ng2-charts": "^4.0.0",
>     "ngx-toastr": "^10.0.4",
>     "oracledb": "^5.3.0",
>     "rxjs": "6.6.3",
>     "stream": "^0.0.2",
>     "timers": "^0.1.1",
>     "tslib": "^2.0.0",
>     "xlsx": "^0.17.4",
>     "xml2js": "^0.4.23",
>     "zone.js": "0.10.3"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "0.1102.1",
>     "@angular/cli": "11.2.1",
>     "@angular/compiler-cli": "11.2.2",
>     "codelyzer": "^6.0.0",
>     "jasmine-core": "~3.6.0",
>     "jasmine-spec-reporter": "~5.0.0",
>     "karma": "~6.1.1",
>     "karma-chrome-launcher": "~3.1.0",
>     "karma-coverage-istanbul-reporter": "~3.0.2",
>     "karma-jasmine": "~4.0.0",
>     "karma-jasmine-html-reporter": "^1.5.0",
>     "protractor": "~7.0.0",
>     "ts-node": "8.6.2",
>     "tslint": "~6.1.0",
>     "typescript": "4.0.5"
>   }

Error occurs after these steps:
npm install 
ng serve

> Error: node_modules/ng2-charts/lib/base-chart.directive.d.ts:39:21 - error TS2694: Namespace '"C:/Users/ac61817/ACS/acs_dashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
> 
> 39     static ɵfac: i0.ɵɵFactoryDeclaration<BaseChartDirective<any, any, any>, never>;
>                        ~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/ng2-charts/lib/base-chart.directive.d.ts:40:21 - error TS2694: Namespace '"C:/Users/ac61817/ACS/acs_dashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.
> 
> 40     static ɵdir: i0.ɵɵDirectiveDeclaration<BaseChartDirective<any, any, any>, "canvas[baseChart]", ["base-chart"], { "type": "type"; "legend": "legend"; "data": "data"; "options": "options"; "plugins": "plugins"; "labels": "labels"; "datasets": "datasets"; }, { "chartClick": "chartClick"; "chartHover": "chartHover"; }, never, never, false>;
>                        ~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/ng2-charts/lib/ng-charts.module.d.ts:14:21 - error TS2694: Namespace '"C:/Users/ac61817/ACS/acs_dashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
> 
> 14     static ɵfac: i0.ɵɵFactoryDeclaration<NgChartsModule, [{ optional: true; }]>;
>                        ~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/ng2-charts/lib/ng-charts.module.d.ts:15:21 - error TS2694: Namespace '"C:/Users/ac61817/ACS/acs_dashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.
> 
> 15     static ɵmod: i0.ɵɵNgModuleDeclaration<NgChartsModule, [typeof i1.BaseChartDirective], never, [typeof i1.BaseChartDirective]>;
>                        ~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/ng2-charts/lib/ng-charts.module.d.ts:16:21 - error TS2694: Namespace '"C:/Users/ac61817/ACS/acs_dashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.
> 
> 16     static ɵinj: i0.ɵɵInjectorDeclaration<NgChartsModule>;
>                        ~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/ng2-charts/lib/ng-charts.module.d.ts:8:21 - error TS2694: Namespace '"C:/Users/ac61817/ACS/acs_dashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
> 
> 8     static ɵfac: i0.ɵɵFactoryDeclaration<NgChartsConfiguration, never>;
>                       ~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/ng2-charts/lib/ng-charts.module.d.ts:9:22 - error TS2694: Namespace '"C:/Users/ac61817/ACS/acs_dashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.[39m
> 
> 9     static ɵprov: i0.ɵɵInjectableDeclaration<NgChartsConfiguration>;
>                        ~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/ng2-charts/lib/theme.service.d.ts:10:21 - error TS2694: Namespace '"C:/Users/ac61817/ACS/acs_dashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.
> 
> 10     static ɵfac: i0.ɵɵFactoryDeclaration<ThemeService, never>;
>                        ~~~~~~~~~~~~~~~~~~~~
> 
> 
> Error: node_modules/ng2-charts/lib/theme.service.d.ts:11:22 - error TS2694: Namespace '"C:/Users/ac61817/ACS/acs_dashboard/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectableDeclaration'.
> 
> 11     static ɵprov: i0.ɵɵInjectableDeclaration<ThemeService>;

And many more like these...

I can not upgrade Angular to higher version as its needed for other existing libraries, or if there is any method to upgrade wisely for all compatible version, then that will be helpful too.

**Comment by visheshmohan** [comment]
**Update**

I downgraded ng2-charts 
` "ng2-charts": "^3.0.0-rc.7",`

Following errors are removed

Now after `ng serve` there are no errors **but** loading app there are these errors:

> Uncaught TypeError: chart_js__WEBPACK_IMPORTED_MODULE_3__.Chart.register is not a function
>     at Module.LPYB (ng-charts.module.ts:32:7)
>     at __webpack_require__ (bootstrap:84:1)
>     at Module.ZAI4 (app.ts:11:47)
>     at __webpack_require__ (bootstrap:84:1)
>     at Module.zUnb (main.ts:1:1)
>     at __webpack_require__ (bootstrap:84:1)
>     at 0 (main.js:11:18)
>     at __webpack_require__ (bootstrap:84:1)
>     at checkDeferredModules (bootstrap:45:1)
>     at Array.webpackJsonpCallback [as push] (bootstrap:32:1)

**Comment by visheshmohan** [comment]
**Resolved**

Followed these steps in sequence:
1. npm install ng2-charts@next --save
2. npm install chart.js --save
3. npm install --save-dev ng2-charts-schematics
4. npm install
5. ng serve -o
