### ISSUE TITLE
Error when I try to set position: 'external' to the tooltip of a doughnut chart

### ISSUE THREAD

**Issue by ManuViola77** [valor-software/ng2-charts#1843]
Im using doughnut chart type with these options: 

```
 donutChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    cutout: 75,
    plugins: {
      tooltip: {
        backgroundColor: 'black',
        position: 'external', <--- this is the problem!
      },
    }
  };
```

Setting the position triggers this error (and doesn't show any tooltip at all):

```
zone.js:177 Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at Tooltip._positionChanged (:4200/vendor.js:192758:52)
    at Tooltip.handleEvent (:4200/vendor.js:192724:34)
    at Object.afterEvent (:4200/vendor.js:192803:25)
    at callback (:4200/vendor.js:194800:15)
    at PluginService._notify (:4200/vendor.js:187831:72)
    at PluginService.notify (:4200/vendor.js:187818:25)
    at Chart.notifyPlugins (:4200/vendor.js:189088:26)
    at Chart._eventHandler (:4200/vendor.js:189118:10)
    at listener (:4200/vendor.js:188990:12)
    at Chart.<anonymous> (:4200/vendor.js:186092:7)
```

I found the error in `chart.js` issues and there was an answer regarding the register:
https://github.com/chartjs/Chart.js/issues/11316#issuecomment-1669974405

What Im trying to achieve is to have the tooltip outside the doughnut circle instead of inside.

I tried with lots of chart.js versions and different ng2-charts versions (I even tried the v6 beta).

**Comment by santam85** [comment]
This seems to be an issue with the Chart.js library, which ng2-charts is simply wrapping. Try using the parameter of `withDefaultRegisterables(...)` to re-register `Tooltip` as the workaround suggests, but it should be addressed in the parent library.
