### ISSUE TITLE
With RC2 BaseChartComponent.ngOnDestroy() gets this.chart.destroy is not a function error

### ISSUE THREAD

**Issue by jkyoutsey** [valor-software/ng2-charts#277]
```
ORIGINAL STACKTRACE:
TypeError: this.chart.destroy is not a function
    at BaseChartComponent.ngOnDestroy (http://localhost:3000/main.bundle.js:18567:25)
```

My components do not implement OnDestroy.  This is just plain lifecycle events.  I nav to a new route and get this error as the chart is destroyed.

**Comment by aicokleinovink** [comment]
Just got the same error:
```
Uncaught EXCEPTION: Error in ./WorkoutStatsComponent class WorkoutStatsComponent - inline template:14:6
ORIGINAL EXCEPTION: TypeError: this.chart.destroy is not a function
ORIGINAL STACKTRACE:
TypeError: this.chart.destroy is not a function
    at BaseChartComponent.ngOnDestroy (http://localhost:8100/build/js/app.bundle.js:88963:24)
    at DebugAppView._View_WorkoutStatsComponent2.destroyInternal (WorkoutStatsComponent.template.js:370:32)
    at DebugAppView.AppView.destroyLocal (http://localhost:8100/build/js/app.bundle.js:33609:14)
    at DebugAppView.destroyLocal (http://localhost:8100/build/js/app.bundle.js:33772:43)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8100/build/js/app.bundle.js:33597:14)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8100/build/js/app.bundle.js:33591:25)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8100/build/js/app.bundle.js:33591:25)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8100/build/js/app.bundle.js:33595:25)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8100/build/js/app.bundle.js:33591:25)
    at DebugAppView.AppView._destroyRecurse (http://localhost:8100/build/js/app.bundle.js:33591:25)
ERROR CONTEXT:
[object Object]Zone.runTask @ zone.js:260ZoneTask.invoke @ zone.js:423
```
This just started to occur after updating to Ionic 2.0.0.beta-8 (with Angular 2 RC). Also can't get the charts to display anymore at all.. But that's another issue..

**Comment by jkyoutsey** [comment]
Moot.  Working with RC3 and 4 just fine.

**Comment by meorfi** [comment]
I have angular RC4, router 3.0.0.beta-2, ng2-charts 1.1.0, chart.js 2.2.0-rc.1... still having that error:
`browser_adapter.ts:82 EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in app/charts/revenue/revenue.chart.component.html:16:16
ORIGINAL EXCEPTION: TypeError: this.chart.destroy is not a function
ORIGINAL STACKTRACE:
TypeError: this.chart.destroy is not a function
    at BaseChartComponent.ngOnDestroy (http://localhost:3000/node_modules/ng2-charts/components/charts/charts.js:38:24)
    at DebugAppView._View_RevenueChartComponent0.destroyInternal (RevenueChartComponent.template.js:528:33)
    at DebugAppView.AppView.destroyLocal (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:175:14)
    at DebugAppView.destroyLocal (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:338:43)
    at DebugAppView.AppView._destroyRecurse (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:163:14)
    at DebugAppView.AppView._destroyRecurse (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:161:25)
    at DebugAppView.AppView._destroyRecurse (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:161:25)
    at DebugAppView.AppView.destroy (http://localhost:3000/node_modules/@angular/core/src/linker/view.js:149:14)
    at ComponentRef_.destroy (http://localhost:3000/node_modules/@angular/core/src/linker/component_factory.js:121:82)
    at RouterOutlet.deactivate (http://localhost:3000/node_modules/@angular/router/src/directives/router_outlet.js:46:28)
ERROR CONTEXT:
[object Object]`
