### ISSUE TITLE
Angular2 RC3 breaks chart creation

### ISSUE THREAD

**Issue by jkyoutsey** [valor-software/ng2-charts#281]
I'll admit up front that this may be an issue with Chart.js.  But I can't be sure...  I'm referencing `chart.js:@2.1.6` and `ng2-charts:@1.1.0`

```javascript
TypeError: t.controllers[o.type] is not a constructor
    at .<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.bundle.min.js:13:8470)
    at Object.r.each (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.bundle.min.js:13:18227)
    at buildOrUpdateControllers (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.bundle.min.js:13:8300)
    at initialize (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.bundle.min.js:13:6662)
    at new t.Controller (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.bundle.min.js:13:6494)
    at new t (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.bundle.min.js:13:30896)
    at BaseChartComponent.getChartBuilder (http://localhost:3000/main.bundle.js:18597:17)
    at BaseChartComponent.refresh (http://localhost:3000/main.bundle.js:18606:28)
    at BaseChartComponent.ngOnInit (http://localhost:3000/main.bundle.js:18525:19)
```

I'm providing mock data to a doughnut chart.
```javascript
  private doughnutChartLabels = ['Critical', 'Warning', 'Good'];
  private doughnutChartType = 'Doughnut';
  private chartData = [ 75, 10, 15 ];
```

```html
  <base-chart class="chart"
    [data]="chartData"
    [labels]="doughnutChartLabels"
    [chartType]="doughnutChartType"
    [colours]="[[192, 57, 43], [241, 196, 15], [39, 174, 96]]"
    [legend]="true"
    (chartHover)="chartHovered($event)"
    (chartClick)="chartClicked($event)"></base-chart>
```

**Comment by valorkin** [comment]
Issue with `doughnutChartType` and `Doughnut` value
please see to http://www.chartjs.org/docs/#doughnut-pie-chart for lower cased names of charts
