### ISSUE TITLE
Problems when using with AOT

### ISSUE THREAD

**Issue by prsolucoes** [valor-software/ng2-charts#426]
Hi,

Im the author of project GoCI that use this library:
https://github.com/prsolucoes/goci

Im trying using the AOT in Angular2, but i have a problem with this library.

The error is:
https://www.dropbox.com/s/fwny3c0py1hllxe/Screenshot%202016-09-23%2023.16.16.png?dl=0

My code is on branch:
https://github.com/prsolucoes/goci/tree/ng2-aot

Thanks for any help :)

**Comment by prsolucoes** [comment]
If you run "npm run build" inside the directory "web-app" you will got the error too:

```
> ngc -p ./tsconfig.json

 66% 732/780 build modulesModuleParseError: Module parse failed: /Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/ngfactory/node_modules/ng2-charts/components/charts/charts.ngfactory.ts Unexpected token (19:59)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (19:59)
    at Parser.pp$4.raise (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$1.parseClass (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/acorn/dist/acorn.js:1087:10)
    at Parser.pp$1.parseStatement (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/acorn/dist/acorn.js:697:19)
    at Parser.pp$1.parseTopLevel (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
    at DependenciesBlock.<anonymous> (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack/lib/NormalModule.js:113:20)
    at DependenciesBlock.onModuleBuild (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 69% 920/921 build modules
```

**Comment by prsolucoes** [comment]
The line inside the file "charts.ngfactory.ts" that the problems happen is:

```
class ChartsModuleInjector extends import0.NgModuleInjector<import1.ChartsModule> {
```

**Comment by prsolucoes** [comment]
Im trying migrate to webpack2, but the errors persists:

```
ERROR in ./ngfactory/~/ng2-charts/components/charts/charts.ngfactory.ts
Module parse failed: /Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/web-app/ngfactory/node_modules/ng2-charts/components/charts/charts.ngfactory.ts Unexpected token (19:59)
You may need an appropriate loader to handle this file type.
| import * as import10 from '@angular/core/src/metadata/view';
| import * as import11 from '@angular/core/src/linker/component_factory';
| class ChartsModuleInjector extends import0.NgModuleInjector<import1.ChartsModule> {
|   _ChartsModule_0:import1.ChartsModule;
|   constructor(parent:import2.Injector) {
 @ ./ngfactory/src/app/job-list/job-list.component.ngfactory.ts 31:15-93
 @ ./ngfactory/src/app/modules/app.module.ngfactory.ts
 @ ./src/main.ts
 @ multi app
```

**Comment by prsolucoes** [comment]
Can anyone help me? Pls :(

**Comment by valorkin** [comment]
no no, npm should not contain .ts files, let me check

**Comment by valorkin** [comment]
try clean install and show me tsconfig.json
check that you have excluded node_modules

**Comment by nikrhes** [comment]
Hi, I got this error while try to run the ng2-chart on angular 2 AOT.

`Export 'ChartsModule' is not defined by '/Users/nikrhes/Documents/digi-aot/app/aot/app/app.module.ngfactory.js'
Export 'ChartsModule' is not defined by '/Users/nikrhes/Documents/digi-aot/app/aot/app/app.module.ngfactory.js'
'ChartsModule' is not exported by node_modules/ng2-charts/components/charts/charts.js (imported by app/app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module`

Can you help me what happens in here? I am already import the ChartsModule on app.module.ts but still got the error. try to solve it by following instuction in here: 

[https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports](url)

but still can't be fixed.

**Comment by prsolucoes** [comment]
Hi,

Check my example here:
https://github.com/prsolucoes/goci-web-app

I have used it too.

**Comment by nikrhes** [comment]
@prsolucoes thanks for your reply. I can see you are using webpack for AOT. I try to use rollup as it is the one suggested by angular documentation. Then maybe the problem is in rollup. thanks!!

**Comment by grapemix** [comment]
I have tried ng-charts with rollup and webpack for different projects. So far, both rollup and webpack failed with ng2-charts in AOT.

**Comment by prsolucoes** [comment]
You can get my project with it working here:
https://github.com/prsolucoes/angular-starter-project
