### ISSUE TITLE
ChartsModule export issue with Ionic RC0

### ISSUE THREAD

**Issue by ng-swapna** [valor-software/ng2-charts#440]
**Reproduction of the problem**

I have a Ionic app (RC0) and updated with ng2-charts version 1.3.0, after compiling the app getting below error. 

`Error: Module c:\Test\node_modules\ng2-charts\ng2-charts.js does not export ChartsModule (imported by c:\Test\.tmp\app\app.module.js)                  
    at Module.trace (c:\Test\node_modules\rollup\dist\rollup.js:7677:29)                                                                                                            
    at ModuleScope.findDeclaration (c:\Test\node_modules\rollup\dist\rollup.js:7300:22)                                                                                             
    at Scope.findDeclaration (c:\Test\node_modules\rollup\dist\rollup.js:5351:39)                                                                                                   
    at Identifier.bind (c:\Test\node_modules\rollup\dist\rollup.js:6489:29)                                                                                                         
    at c:\Test\node_modules\rollup\dist\rollup.js:5151:50                                                                                                                           
    at ArrayExpression.eachChild (c:\Test\node_modules\rollup\dist\rollup.js:5165:19)                                                                                               
    at ArrayExpression.bind (c:\Test\node_modules\rollup\dist\rollup.js:5151:7)                                                                                                     
    at c:\Test\node_modules\rollup\dist\rollup.js:5151:50                                                                                                                           
    at Node.eachChild (c:\Test\node_modules\rollup\dist\rollup.js:5168:5)                                                                                                           
    at Node.bind (c:\Test\node_modules\rollup\dist\rollup.js:5151:7)`

Thanks in advance.

**Comment by sjaanus** [comment]
I have run into same problem.

**Comment by TomDemulierChevret** [comment]
Hi,

I've run into the same problem and managed to work around it by replacing :

`import {ChartsModule} from "ng2-charts";`

with

`import {ChartsModule} from "ng2-charts/components/charts/charts";`

If you struggle to include the chart.js (or chart.bundle.js) into the index.html because of Ionic RC0 new build system, please read : https://forum.ionicframework.com/t/rc0-injecting-custom-scripts/65281/4 &  https://www.npmjs.com/package/@ionic/app-scripts

**Comment by rafaelss95** [comment]
I have the same problem and the above solution didn't work for me.

**Comment by sjaanus** [comment]
TomDemulierChevret solution worked for me.

**Comment by rafaelss95** [comment]
I'm getting the following error:

> Error: src/app/app.module.ts(7,30): error TS2307: Cannot find module 'ng2-charts/components/charts/charts'.

**Comment by iamyojimbo** [comment]
You need to make sure you have the latest version installed. Just try removing your `package.json`

**Comment by danbucholtz** [comment]
Dan from Ionic here. We're going to provide some instructions to Angular library creators (and really any library creators) on how to distribute their `dist` directory with `commonjs` modules AND `es2015` modules and link them up in the `package.json` using the `main` and `module` fields.

Once this library follows the Angular convention, everything will just work.

Expect that in the coming week or so.

Thanks,
Dan

**Comment by larssn** [comment]
Can you hint at how to do that, for those of us that are familiar with the build system already?

**Comment by magicfa** [comment]
have you tried to put it into rollup.config.js located in node_modules/@ionic/app-scripts/config

I did it with firebase and angularfire and that works well

  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    ngTemplate(),
    commonjs({
      include: [
        'node_modules/rxjs/**',
        'node_modules/firebase/**',
        'node_modules/angularfire2/**',
        'node_modules/@ionic/storage/**',
        'node_modules/localforage/**'
      ],
      namedExports: {
        'node_modules/firebase/firebase.js': ['initializeApp', 'auth', 'database'],
        'node_modules/angularfire2/node_modules/firebase/firebase-browser.js': ['initializeApp', 'auth', 'database']
      }
    }),

**Comment by victorcarvalhosp** [comment]
@danbucholtz any news on this?

Thanks!

**Comment by ng-swapna** [comment]
I directly moved chart.js files like below and made some code changes it started working.

![image](https://cloud.githubusercontent.com/assets/17465929/21092997/72652bf2-c075-11e6-8f83-9e81e944b0b5.png)

`<canvas baseChart class="chart" [datasets]="orderSummaryChartData" [labels]="orderSummaryChartLabels" [chartType]="doughnutChartType"
						(chartHover)="chartHovered($event)" (chartClick)="chartClicked($event)" [colors]="colors">
					</canvas>`
