### ISSUE TITLE
Components containing ng2-charts fail Karma test

### ISSUE THREAD

**Issue by rocklob** [valor-software/ng2-charts#570]
I'm new to Angular 2, but I've been using Angular CLI to help develop my projects.  When using ng2-charts with Angular CLI's automatically created spec files for components, the basic "should create" unit tests fail when those components contain ng2-charts.  Note that even though the tests fail, the chart actually works when manually viewed via via `ng serve`.

**Reproduction of the problem**

1. Create a new project using Angular CLI and install ng2-charts.

```
ng new ng2charts
cd ng2charts
npm install ng2-charts --save
npm install chart.js --save
```

2. Update `angular-cli.json` to include charts scripts.

```
...
  "scripts": [
    "../node_modules/chart.js/dist/Chart.min.js",
    "../node_modules/chart.js/src/chart.js"
  ],
...
```

3. Add ChartsModule to `app.module.ts`:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpModule } from '@angular/http';
import { AppComponent } from './app.component';

import { ChartsModule } from 'ng2-charts/ng2-charts';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    HttpModule,
    ChartsModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

4. Add chart 

`app.component.html`:

```
<div style="display: block;">
    <canvas baseChart class="chart" [datasets]="mainChartData" [labels]="mainChartLabels" chartType="line"></canvas>
</div>
```

`app.component.ts`:

```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
    constructor( ) { }

    public mainChartData:Array<any> = [
        {
            data: [3,8,7,4,3,6,1],
            label: 'Foo'
        }
    ];
    public mainChartLabels:Array<any> = ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'];
}

```

5. Create a test in `app.component.spec.ts` (this is basically what Angular CLI creates automatically when you generate components with `--spec=true`):

```
import { TestBed, async } from '@angular/core/testing';
import { AppComponent } from './app.component';
import { RouterTestingModule } from '@angular/router/testing';
import { ChartsModule }                 from 'ng2-charts/ng2-charts';

describe('Chart', () => {
  let component: AppComponent;
  let fixture: ComponentFixture<AppComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [ ChartsModule ],
      declarations: [ AppComponent ]
    })
    .compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(AppComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});

```

6. `ng serve` to verify that this works.

7. However, `ng test` fails...

```
$ ng test --single-run
13 01 2017 13:45:49.299:WARN [watcher]: Pattern "/Users/foo/Documents/sandbox/ng2ctest/src/assets/**" does not match any file.
13 01 2017 13:45:55.926:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
13 01 2017 13:45:55.926:INFO [launcher]: Launching browser Chrome with unlimited concurrency
13 01 2017 13:45:55.950:INFO [launcher]: Starting browser Chrome
13 01 2017 13:45:56.750:INFO [Chrome 55.0.2883 (Mac OS X 10.12.2)]: Connected on socket /#_CRF5z6C5c6iwMIZAAAA with id 52259825
Chrome 55.0.2883 (Mac OS X 10.12.2) Chart should create FAILED
	Error: Error in ./AppComponent class AppComponent - inline template:2:90 caused by: ng2-charts configuration issue: Embedding Chart.js lib is mandatory
	Error: ng2-charts configuration issue: Embedding Chart.js lib is mandatory
	    at BaseChartDirective.getChartBuilder (webpack:///~/ng2-charts/components/charts/charts.js:71:0 <- src/test.ts:70047:19) [angular]
	    at BaseChartDirective.refresh (webpack:///~/ng2-charts/components/charts/charts.js:114:0 <- src/test.ts:70090:27) [angular]
	    at BaseChartDirective.ngOnInit (webpack:///~/ng2-charts/components/charts/charts.js:18:0 <- src/test.ts:69994:18) [angular]
	    at Wrapper_BaseChartDirective.ngDoCheck (/ChartsModule/BaseChartDirective/wrapper.ngfactory.js:97:53) [angular]
	    at CompiledTemplate.proxyViewClass.View_AppComponent0.detectChangesInternal (/DynamicTestModule/AppComponent/component.ngfactory.js:53:32) [angular]
	    at CompiledTemplate.proxyViewClass.AppView.detectChanges (webpack:///~/@angular/core/src/linker/view.js:425:0 <- src/test.ts:64208:14) [angular]
	    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (webpack:///~/@angular/core/src/linker/view.js:620:0 <- src/test.ts:64403:44) [angular]
	    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (webpack:///~/@angular/core/src/linker/view.js:410:0 <- src/test.ts:64193:18) [angular]
	    at CompiledTemplate.proxyViewClass.View_AppComponent_Host0.detectChangesInternal (/DynamicTestModule/AppComponent/host.ngfactory.js:29:19) [angular]
	    at CompiledTemplate.proxyViewClass.AppView.detectChanges (webpack:///~/@angular/core/src/linker/view.js:425:0 <- src/test.ts:64208:14) [angular]
	    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (webpack:///~/@angular/core/src/linker/view.js:620:0 <- src/test.ts:64403:44) [angular]
	    at ViewRef_.detectChanges (webpack:///~/@angular/core/src/linker/view_ref.js:179:0 <- src/test.ts:46130:20) [angular]
	    at ComponentFixture._tick (webpack:///~/@angular/core/bundles/core-testing.umd.js:191:0 <- src/test.ts:17544:36) [angular]
	    at webpack:///~/@angular/core/bundles/core-testing.umd.js:205:45 <- src/test.ts:17558:53 [angular]
Chrome 55.0.2883 (Mac OS X 10.12.2): Executed 1 of 1 (1 FAILED) ERROR (0.293 secs / 0.118 secs)
```

## ng version output
```
angular-cli: 1.0.0-beta.24
node: 6.8.1
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3
```

**Comment by m0t0r** [comment]
@rocklob add `import 'chart.js';` into `test.ts`

**Comment by rocklob** [comment]
That works, thank you @m0t0r!
