### ISSUE TITLE
Exception at BaseChartDirective.ngOnInit

### ISSUE THREAD

**Issue by s10863** [valor-software/ng2-charts#734]
I'm having issues with using sample chart code. I've created new angular2 project using ASP.NET Core template and below commands:

> dotnet new --install Microsoft.AspNetCore.SpaTemplates::*
> dotnet new angular

After this i've installed ng2-charts and copied example code of the first chart. But i'm receiving exception while trying to run it:

An unhandled exception occurred while processing the request.

```
Exception: Call to Node module failed with error: Error: Uncaught (in promise): TypeError: this.element.nativeElement.getContext is not a function
TypeError: this.element.nativeElement.getContext is not a function
at BaseChartDirective.ngOnInit (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\main-server.js:661:47)
at Wrapper_BaseChartDirective.ngDoCheck (/ChartsModule/BaseChartDirective/wrapper.ngfactory.js:96:53)
at CompiledTemplate.proxyViewClass.View_HomeComponent0.detectChangesInternal (/AppModule/HomeComponent/component.ngfactory.js:200:33)
at CompiledTemplate.proxyViewClass.AppView.detectChanges (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:12281:18)
at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:12266:22)
at CompiledTemplate.proxyViewClass.View_HomeComponent_Host0.detectChangesInternal (/AppModule/HomeComponent/host.ngfactory.js:27:19)
at CompiledTemplate.proxyViewClass.AppView.detectChanges (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:12281:18)
at ViewRef_.detectChanges (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:9450:24)
at RouterOutlet.activate (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:88407:46)
at ActivateRoutes.placeComponentIntoOutlet (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:87686:20)
at ActivateRoutes.activateRoutes (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:87653:30)
at C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:87589:62
at Array.forEach (native)
at ActivateRoutes.activateChildRoutes (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:87589:33)
at ActivateRoutes.activate (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:87563:18)
at resolvePromise (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:74515:31) [angular]
at resolvePromise (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:74486:17) [angular]
at C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:74563:17 [angular]
at Object.onInvokeTask (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:4044:41) [angular]
at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:74216:36) [angular]
at Zone.module.exports.Zone.runTask (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:74016:47) [<root> => angular]
at drainMicroTaskQueue (C:\Users\s10863\Documents\Visual Studio 2017\Projects\Test\TestMonitor\ClientApp\dist\vendor.js:74396:35) [<root>]
at runMicrotasksCallback (internal/process/next_tick.js:64:5) [<root>]
at _combinedTickCallback (internal/process/next_tick.js:73:7) [<root>]
at process._tickCallback (internal/process/next_tick.js:104:9) [<root>]
```

**Comment by qu1ckdry** [comment]
I have the same issue, did you make any progress on it?

**Comment by s10863** [comment]
Sadly but no :/

**Comment by davidemanske** [comment]
ditto.

**Comment by qu1ckdry** [comment]
I can get it working if I disable prerendering:
Replace:
`<app asp-prerender-module="ClientApp/dist/main-server">Loading...</app>`
With:
`<app>Loading...</app>`

And if I reference the Chart.js CDN:
Replace:
`<script src="node_modules/chart.js/src/chart.js"></script>`
With:
`<script src=https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js></script>`

I'd like to keep the prerendering but it does seem to have a problem with a few packages... Anyone know of a work around?

**Comment by s10863** [comment]
i used your way and it works now, but still i would also want prerendering enabled, any progress at this?

**Comment by kroonwijk** [comment]
Finally ... after hours of investigation, trial and error, the solution of @qu1ckdry helped me out. Plus the fact that in that generated asp.net core template, you need to import the ChartsModule in the `app.module.shared.ts` file, and not in the `app.module.client.ts` or `app.module.server.ts` files. That only becomes apparent when you understand the concept of pre-rendering, and asking myself:   "why does the server complain about this, and not the browser".

**Comment by paviad** [comment]
This package is now updated for Angular 7. If this issue persists, please provide a codepen/stackblitz/... example showing the issue.
