### ISSUE TITLE
http://localhost:3000/chart.js 404 (Not Found)

### ISSUE THREAD

**Issue by marianfaryna** [valor-software/ng2-charts#901]
Even using provided example template
http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

this error is shown in console when trying to load chart.

`Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/chart.js
	Error: XHR error (404 Not Found) loading http://localhost:3000/chart.js
	    at XMLHttpRequest.wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17)
	Error loading http://localhost:3000/chart.js as "chart.js" from http://localhost:3000/node_modules/ng2-charts/charts/charts.js
	    at XMLHttpRequest.wrapFn (http://localhost:3000/node_modules/zone.js/dist/zone.js:1166:39)
	    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:425:31)
	    at Zone.runTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:192:47)
	    at ZoneTask.invokeTask [as invoke] (http://localhost:3000/node_modules/zone.js/dist/zone.js:499:34)
	    at invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:1540:14)
	    at XMLHttpRequest.globalZoneAwareCallback (http://localhost:3000/node_modules/zone.js/dist/zone.js:1566:17)
	Error loading http://localhost:3000/chart.js as "chart.js" from http://localhost:3000/node_modules/ng2-charts/charts/charts.js`

I have ng2-charts and chartjs installed by npm
and both them are in node_modules directory

my index.html <head>
`    <script src="node_modules/core-js/client/shim.min.js"></script>

    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <script src="node_modules/chart.js/dist/Chart.bundle.min.js"></script>

    <script src="systemjs.config.js"></script>
    <script>
      System.import('main.js').catch(function(err){ console.error(err); });
    </script>
  </head>`

systemjs.config.js

`map {
...
      'ng2-charts': 'node_modules/ng2-charts',
...
}
packages: {
...
'ng2-charts': { main: 'ng2-charts.js', defaultExtension: 'js' }
...
}`

module.ts

`import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent }  from './app.component';
import { ChartsModule } from 'ng2-charts/ng2-charts';

@NgModule({
  imports:      [ BrowserModule, ChartsModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }`

**Comment by marianfaryna** [comment]
Found the problem. I needed to update systemjs.config.js with 

`map { ...
"chart.js": "npm:chart.js/dist/chart.js",
...
}`
